// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class RegistroEventosDto
    {
        /// <summary>
        ///  Id identificador de la tabla
        /// </summary>
        public long EvtId { get; set; }
        /// <summary>
        /// Número que hace referencia al ID del tipo de evento
        /// </summary>
        public int? TpevtId { get; set; }
        /// <summary>
        /// Id identificador del usuario del sistema que realizará el evento
        /// </summary>
        public int? EvtUsuId { get; set; }
        /// <summary>
        /// Detalles del evento
        /// </summary>
        public string EvtDetalles { get; set; }
        /// <summary>
        /// Navegador del usuario que realizará el evento
        /// </summary>
        public string EvtUserAgent { get; set; }
        /// <summary>
        /// Dirección IP del usuario que realizará el evento
        /// </summary>
        public string EvtDireccionIP { get; set; }
        /// <summary>
        /// Estado anterior del evento
        /// </summary>
        public string EvtEstadoAnterior { get; set; }
        /// <summary>
        /// Nuevo estado del evento
        /// </summary>
        public string EvtNuevoEstado { get; set; }
        /// <summary>
        /// Fecha de creación del evento
        /// </summary>
        public DateTime? EvtFechaCreacion { get; set; }
    }
}