// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class UsuariosDto
    { 
        public int usuId { get; set; }
        public int EmpId { get; set; }
        public string UsuNombre { get; set; }
        public int? ConId { get; set; }
        public int? UsuContrasenaRecuperacion { get; set; }
        public int RolId { get; set; }
        public string UsuIp { get; set; }
        public bool? UsuEsActivo { get; set; }
        public bool? UsuSuspendido { get; set; }
        public bool? UsuEsEliminado { get; set; }
        public DateTime? UsuFechaCreacion { get; set; }
        public DateTime? UsufechaModificacion { get; set; } 
    }
}