// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbEmpleadosConfiguration : IEntityTypeConfiguration<tbEmpleados>
    {
        public void Configure(EntityTypeBuilder<tbEmpleados> entity)
        {
            entity.HasKey(e => e.emp_Id);

            entity.ToTable("tbEmpleados", "Refugio");

            entity.HasIndex(e => e.emp_Codigo, "UQ_tbEmpleados_Codigo")
                .IsUnique();

            entity.Property(e => e.emp_Id).HasComment("Identificador único de la tabla Empleados.");

            entity.Property(e => e.emp_Codigo)
                .IsRequired()
                .HasMaxLength(7)
                .IsUnicode(false);

            entity.Property(e => e.emp_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.HasOne(d => d.cag)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.cag_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbEmpleados_tbEmpleadosCargos");

            entity.HasOne(d => d.per)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.per_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.refg)
                .WithMany(p => p.tbEmpleados)
                .HasForeignKey(d => d.refg_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEmpleados> entity);
    }
}
