// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbEmpleadosCargosConfiguration : IEntityTypeConfiguration<tbEmpleadosCargos>
    {
        public void Configure(EntityTypeBuilder<tbEmpleadosCargos> entity)
        {
            entity.HasKey(e => e.cag_Id);

            entity.ToTable("tbEmpleadosCargos", "Refugio");

            entity.Property(e => e.cag_Id).HasComment("Identificador único de la tabla Empleados Cargos.");

            entity.Property(e => e.cag_Descripcion)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.cag_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.cag_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.cag_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.cag_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.cag_Salario).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.cag_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.cag_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.cag_UsuarioCreaNavigation)
                .WithMany(p => p.tbEmpleadosCargos)
                .HasForeignKey(d => d.cag_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbEmpleadosCargos_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEmpleadosCargos> entity);
    }
}
