// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbEntradasConfiguration : IEntityTypeConfiguration<tbEntradas>
    {
        public void Configure(EntityTypeBuilder<tbEntradas> entity)
        {
            entity.HasKey(e => e.ent_Id);

            entity.ToTable("tbEntradas", "Inventario");

            entity.Property(e => e.ent_Id).HasComment("Identificador único de la tabla Entradas.");

            entity.Property(e => e.ent_Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("Información descriptiva de la entrada.");

            entity.Property(e => e.ent_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.ent_Fecha).HasColumnType("datetime");

            entity.Property(e => e.ent_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.ent_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.ent_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.ent_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.Property(e => e.refg_Id).HasComment("Este es el ID del departamento que hace referencia al primary key de la tabla tbRefugios");

            entity.HasOne(d => d.ent_UsuarioCreaNavigation)
                .WithMany(p => p.tbEntradas)
                .HasForeignKey(d => d.ent_UsuarioCrea)
                .HasConstraintName("FK_Inventario_tbEntradas_tbUsuarios_usu_Id");

            entity.HasOne(d => d.refg)
                .WithMany(p => p.tbEntradas)
                .HasForeignKey(d => d.refg_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEntradas> entity);
    }
}
