// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbEventosConfiguration : IEntityTypeConfiguration<tbEventos>
    {
        public void Configure(EntityTypeBuilder<tbEventos> entity)
        {
            entity.HasKey(e => e.eve_Id)
                .HasName("PK_tbRegistroVoluntariado");

            entity.ToTable("tbEventos", "Refugio");

            entity.Property(e => e.eve_Id).HasComment("Identificador único de la tabla Eventos.");

            entity.Property(e => e.eve_Descripcion)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.eve_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.eve_Fecha).HasColumnType("date");

            entity.Property(e => e.eve_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.eve_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.eve_HoraFinal).HasColumnType("time(2)");

            entity.Property(e => e.eve_HoraInicio).HasColumnType("time(2)");

            entity.Property(e => e.eve_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.eve_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.eve_UsuarioCreaNavigation)
                .WithMany(p => p.tbEventos)
                .HasForeignKey(d => d.eve_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbEventos_tbUsuarios_usu_Id");

            entity.HasOne(d => d.refg)
                .WithMany(p => p.tbEventos)
                .HasForeignKey(d => d.refg_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEventos> entity);
    }
}
