// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbMunicipiosConfiguration : IEntityTypeConfiguration<tbMunicipios>
    {
        public void Configure(EntityTypeBuilder<tbMunicipios> entity)
        {
            entity.HasKey(e => e.mpio_Id)
                .HasName("PK_General_tbMunicipios_mpio_Id");

            entity.ToTable("tbMunicipios", "General");

            entity.HasComment("");

            entity.Property(e => e.mpio_Id).HasComment("Identificador único de la tabla Municipios.");

            entity.Property(e => e.mpio_Codigo)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);

            entity.Property(e => e.mpio_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("alguna descrip");

            entity.Property(e => e.mpio_EsEliminado).HasComment("ssssssfdfdf");

            entity.Property(e => e.mpio_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.mpio_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.mpio_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.mpio_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.depto)
                .WithMany(p => p.tbMunicipios)
                .HasForeignKey(d => d.depto_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_General_tbDepartamentos_tbMunicipios_depto_Id");

            entity.HasOne(d => d.mpio_UsuarioCreaNavigation)
                .WithMany(p => p.tbMunicipios)
                .HasForeignKey(d => d.mpio_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_General_tbMunicipios_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbMunicipios> entity);
    }
}
