// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbSolicitudesConfiguration : IEntityTypeConfiguration<tbSolicitudes>
    {
        public void Configure(EntityTypeBuilder<tbSolicitudes> entity)
        {
            entity.HasKey(e => e.sol_Id);

            entity.ToTable("tbSolicitudes", "Refugio");

            entity.Property(e => e.sol_Id).HasComment("Identificador único del registro.");

            entity.Property(e => e.masc_Id).HasComment("Identificador de la mascota.");

            entity.Property(e => e.sol_Apellidos)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Apellido de la persona que realiza la solicitud.");

            entity.Property(e => e.sol_Correo)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Servicio de red que permite la comunicación mediante correo eleectronico con el solicitante.");

            entity.Property(e => e.sol_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.sol_Fecha)
                .HasColumnType("datetime")
                .HasComment("pendiente eliminar");

            entity.Property(e => e.sol_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.sol_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.sol_Identidad)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasComment("Identificador nacional de la persona.");

            entity.Property(e => e.sol_Nombres)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Nombre de la persona realiza la solicitud.");

            entity.Property(e => e.sol_Telefono)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasComment("Numero de teléfono que corresponde al solicitante.");

            entity.Property(e => e.sol_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.masc)
                .WithMany(p => p.tbSolicitudes)
                .HasForeignKey(d => d.masc_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.sol_UsuarioCreaNavigation)
                .WithMany(p => p.tbSolicitudes)
                .HasForeignKey(d => d.sol_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbSolicitudes_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbSolicitudes> entity);
    }
}
