// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbVacunasConfiguration : IEntityTypeConfiguration<tbVacunas>
    {
        public void Configure(EntityTypeBuilder<tbVacunas> entity)
        {
            entity.HasKey(e => e.vac_Id);

            entity.ToTable("tbVacunas", "Refugio");

            entity.Property(e => e.vac_Id).HasComment("Identificador único de la tabla Vacunas.");

            entity.Property(e => e.vac_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("Nombre de la vacuna.");

            entity.Property(e => e.vac_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.vac_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.vac_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.vac_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.vac_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.vac_UsuarioCreaNavigation)
                .WithMany(p => p.tbVacunas)
                .HasForeignKey(d => d.vac_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbVacunas_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbVacunas> entity);
    }
}
