// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbAdopcionesConfiguration : IEntityTypeConfiguration<tbAdopciones>
    {
        public void Configure(EntityTypeBuilder<tbAdopciones> entity)
        {
            entity.HasKey(e => e.adop_Id)
                .HasName("PK__tbFichaA__4F1E49E6323B890F");

            entity.ToTable("tbAdopciones", "Refugio");

            entity.Property(e => e.adop_FechaCrea).HasColumnType("datetime");

            entity.Property(e => e.adop_FechaModifica).HasColumnType("datetime");

            entity.HasOne(d => d.adop_UsuarioCreaNavigation)
                .WithMany(p => p.tbAdopciones)
                .HasForeignKey(d => d.adop_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbAdopciones_tbUsuarios_usu_Id");

            entity.HasOne(d => d.sol)
                .WithMany(p => p.tbAdopciones)
                .HasForeignKey(d => d.sol_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbAdopciones> entity);
    }
}
