// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbCategoriasConfiguration : IEntityTypeConfiguration<tbCategorias>
    {
        public void Configure(EntityTypeBuilder<tbCategorias> entity)
        {
            entity.HasKey(e => e.cat_Id)
                .HasName("PK_tbCategoriaInventario");

            entity.ToTable("tbCategorias", "Inventario");

            entity.Property(e => e.cat_Id).HasComment("Identificador único de la tabla Categorias.");

            entity.Property(e => e.cat_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.cat_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.cat_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.cat_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.cat_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.cat_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.cat_UsuarioCreaNavigation)
                .WithMany(p => p.tbCategorias)
                .HasForeignKey(d => d.cat_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Inventario_tbCategorias_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbCategorias> entity);
    }
}
