// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbComportamientosConfiguration : IEntityTypeConfiguration<tbComportamientos>
    {
        public void Configure(EntityTypeBuilder<tbComportamientos> entity)
        {
            entity.HasKey(e => e.com_Id);

            entity.ToTable("tbComportamientos", "Refugio");

            entity.Property(e => e.com_Descripcion)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.com_FechaCrea).HasColumnType("datetime");

            entity.Property(e => e.com_FechaModifica).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbComportamientos> entity);
    }
}
