// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbDepartamentosConfiguration : IEntityTypeConfiguration<tbDepartamentos>
    {
        public void Configure(EntityTypeBuilder<tbDepartamentos> entity)
        {
            entity.HasKey(e => e.depto_Id)
                .HasName("PK_General_tbDepartamentos_depto_Id");

            entity.ToTable("tbDepartamentos", "General");

            entity.HasIndex(e => e.depto_Descripcion, "UQ_General_tbDepartamentos_depto_Descripcion")
                .IsUnique();

            entity.Property(e => e.depto_Id).HasComment("Identificador único de la tabla Departamentos.");

            entity.Property(e => e.depto_Codigo)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasComment("Código administrativo único del departamento.");

            entity.Property(e => e.depto_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("Nombre del departamento.");

            entity.Property(e => e.depto_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.depto_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.depto_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.depto_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.depto_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.depto_UsuarioCreaNavigation)
                .WithMany(p => p.tbDepartamentos)
                .HasForeignKey(d => d.depto_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_General_tbDepartamentos_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbDepartamentos> entity);
    }
}
