// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbEventos_tbVoluntariosConfiguration : IEntityTypeConfiguration<tbEventos_tbVoluntarios>
    {
        public void Configure(EntityTypeBuilder<tbEventos_tbVoluntarios> entity)
        {
            entity.HasKey(e => e.evevol_Id);

            entity.ToTable("tbEventos_tbVoluntarios", "Refugio");

            entity.HasOne(d => d.eve)
                .WithMany(p => p.tbEventos_tbVoluntarios)
                .HasForeignKey(d => d.eve_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbEventos_tbVoluntarios_tbEventos_eve");

            entity.HasOne(d => d.vol)
                .WithMany(p => p.tbEventos_tbVoluntarios)
                .HasForeignKey(d => d.vol_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbEventos_tbVoluntarios> entity);
    }
}
