// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbItemsConfiguration : IEntityTypeConfiguration<tbItems>
    {
        public void Configure(EntityTypeBuilder<tbItems> entity)
        {
            entity.HasKey(e => e.itm_Id);

            entity.ToTable("tbItems", "Inventario");

            entity.Property(e => e.itm_Id).HasComment("Identificador único de la tabla Items.");

            entity.Property(e => e.itm_Codigo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.itm_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.itm_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.itm_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.itm_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.itm_Precio).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.itm_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.itm_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.cat)
                .WithMany(p => p.tbItems)
                .HasForeignKey(d => d.cat_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbItems_tbInventariosCategorias_cat_Id");

            entity.HasOne(d => d.itm_UsuarioCreaNavigation)
                .WithMany(p => p.tbItems)
                .HasForeignKey(d => d.itm_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Inventario_tbItems_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbItems> entity);
    }
}
