// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbMascotasConfiguration : IEntityTypeConfiguration<tbMascotas>
    {
        public void Configure(EntityTypeBuilder<tbMascotas> entity)
        {
            entity.HasKey(e => e.masc_Id)
                .HasName("PK__tbMascot__D4743CE4095775B4");

            entity.ToTable("tbMascotas", "Refugio");

            entity.Property(e => e.masc_Id).HasComment("Identificador único de la tabla Mascotas.");

            entity.Property(e => e.masc_Color)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.masc_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.masc_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.masc_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.masc_Historia).HasMaxLength(500);

            entity.Property(e => e.masc_Imagen).HasColumnType("image");

            entity.Property(e => e.masc_Nombre)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.masc_Peso).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.masc_Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.masc_UsuarioCrea).HasComment("Indica el identificador del usuario que creó el registro.");

            entity.Property(e => e.masc_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.masc_UsuarioCreaNavigation)
                .WithMany(p => p.tbMascotas)
                .HasForeignKey(d => d.masc_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbMascotas_tbUsuarios_usu_Id");

            entity.HasOne(d => d.proc)
                .WithMany(p => p.tbMascotas)
                .HasForeignKey(d => d.proc_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.raza)
                .WithMany(p => p.tbMascotas)
                .HasForeignKey(d => d.raza_Id);

            entity.HasOne(d => d.refg)
                .WithMany(p => p.tbMascotas)
                .HasForeignKey(d => d.refg_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbMascotas_tbRefugios_medic_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbMascotas> entity);
    }
}
