// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbRefugiosConfiguration : IEntityTypeConfiguration<tbRefugios>
    {
        public void Configure(EntityTypeBuilder<tbRefugios> entity)
        {
            entity.HasKey(e => e.refg_Id)
                .HasName("PK__tbAlberg__86A34756F46FB6ED");

            entity.ToTable("tbRefugios", "Refugio");

            entity.Property(e => e.refg_Id).HasComment("Identificador único de la tabla Refugios.");

            entity.Property(e => e.refg_Correo)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.refg_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.refg_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.refg_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.refg_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.refg_InformacionAdicional).HasMaxLength(500);

            entity.Property(e => e.refg_Nombre)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.refg_RTN)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false);

            entity.Property(e => e.refg_Telefono)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);

            entity.Property(e => e.refg_Ubicacion)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.refg_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.refg_UsuarioCreaNavigation)
                .WithMany(p => p.tbRefugios)
                .HasForeignKey(d => d.refg_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbRefugios_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbRefugios> entity);
    }
}
