// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbUsuariosConfiguration : IEntityTypeConfiguration<tbUsuarios>
    {
        public void Configure(EntityTypeBuilder<tbUsuarios> entity)
        {
            entity.HasKey(e => e.usu_Id);

            entity.ToTable("tbUsuarios", "Seguridad");

            entity.Property(e => e.Usu_EsActivo)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.Usu_EsEliminado).HasDefaultValueSql("((0))");

            entity.Property(e => e.Usu_FechaCreacion).HasColumnType("datetime");

            entity.Property(e => e.Usu_Ip)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.Usu_Nombre)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Usu_Suspendido).HasDefaultValueSql("((0))");

            entity.Property(e => e.Usu_fechaModificacion).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbUsuarios> entity);
    }
}
