// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PetsHome.Common.AppPetshomeDbContext;
using PetsHome.Common.Entities;
using System;

namespace PetsHome.Common.AppPetshomeDbContext.Configurations
{
    public partial class tbVoluntariosConfiguration : IEntityTypeConfiguration<tbVoluntarios>
    {
        public void Configure(EntityTypeBuilder<tbVoluntarios> entity)
        {
            entity.HasKey(e => e.vol_Id)
                .HasName("PK__tbVolunt__31589030C0D6F266");

            entity.ToTable("tbVoluntarios", "Refugio");

            entity.Property(e => e.vol_Id).HasComment("Identificador único de la tabla Voluntarios.");

            entity.Property(e => e.vol_EsEliminado).HasComment("Indica si el registro está desactivado permanentemente.");

            entity.Property(e => e.vol_FechaCrea)
                .HasColumnType("datetime")
                .HasComment("Registra la fecha en que se creó el registro.");

            entity.Property(e => e.vol_FechaModifica)
                .HasColumnType("datetime")
                .HasComment("Registra la última fecha en que se modificó el registro.");

            entity.Property(e => e.vol_Recurrente).HasDefaultValueSql("((0))");

            entity.Property(e => e.vol_UsuarioModifica).HasComment("Indica el identificador del último usuario que modificó el registro.");

            entity.HasOne(d => d.per)
                .WithMany(p => p.tbVoluntarios)
                .HasForeignKey(d => d.per_Id)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.vol_UsuarioCreaNavigation)
                .WithMany(p => p.tbVoluntarios)
                .HasForeignKey(d => d.vol_UsuarioCrea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refugio_tbVoluntarios_tbUsuarios_usu_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tbVoluntarios> entity);
    }
}
