// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Albergue_Solicitudes_DeleteResult
    {
    }
}
