// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_Usuarios_Login_V2RolesResult
    {
        public int rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
    }
}