// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_GetUserPermissionsResult
    {
        public string Pantalla { get; set; }
        public string Permiso { get; set; }
        public string Modulo { get; set; }
        public int modpt_Id { get; set; }
    }
}