// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_Usuarios_DetailResult
    {
        public int usu_Id { get; set; }
        public int Emp_Id { get; set; }
        public string Usu_Nombre { get; set; }
        public string Emp_Nombres { get; set; }
        public string Emp_Apellidos { get; set; }
        public int Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public string Usu_Ip { get; set; }
        public bool? Usu_EsActivo { get; set; }
        public bool? Usu_Suspendido { get; set; }
        public DateTime? Usu_FechaCreacion { get; set; }
        public DateTime? Usu_fechaModificacion { get; set; }
    }
}