// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_PantallasPorRol_PantallasResult
    {
        public int modpt_Id { get; set; }
        public int mod_Id { get; set; }
        public string modpt_Descripcion { get; set; }
        public string modpt_Url { get; set; }
        public string modpt_Icono { get; set; }
        public int? modpt_Orden { get; set; }
        public string Mod_Nombre { get; set; }
        public string comp_Descripcion { get; set; }
    }
}