// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_GetUserPantallasResult
    {
        public string Pantalla { get; set; }
    }
}