// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_Roles_ListResult
    {
        public int Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public bool? Rol_EsActivo { get; set; }
        public DateTime? Rol_FechaCreacion { get; set; }
    }
}