// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_RolesUsuarios_ListResult
    {
        public int rol_usu_Id { get; set; }
        public int rol_Id { get; set; }
        public int usu_Id { get; set; }
        public DateTime rol_usu_FechaAsignacion { get; set; }
        public string Rol_Descripcion { get; set; }
        public string Usu_Nombre { get; set; }
        public string Emp_NombreCompleto { get; set; }
    }
}