// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_RolModulosPantallas_ListResult
    {
        public int rolpt_Id { get; set; }
        public int modpt_Id { get; set; }
        public int rol_Id { get; set; }
        public DateTime rolpt_FechaAsignacion { get; set; }
        public string modpt_Descripcion { get; set; }
        public string modpt_Url { get; set; }
        public string Mod_Nombre { get; set; }
        public string Rol_Descripcion { get; set; }
    }
}