// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_Componentes_ListResult
    {
        public int comp_Id { get; set; }
        public string comp_Descripcion { get; set; }
    }
}