// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetsHome.Common.Entities
{
    public partial class PR_Seguridad_Roles_GetPermissionsResult
    {
        public string Rol_Descripcion { get; set; }
        public string Mod_Nombre { get; set; }
        public string Mod_Descripcion { get; set; }
        public string Mod_Icono { get; set; }
        public string Mod_Url { get; set; }
        public int? Mod_Orden { get; set; }
        public string Permisos { get; set; }
    }
}