// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbModulosPantallas
    {
        public tbModulosPantallas()
        {
            tbRolModulosPantallas = new HashSet<tbRolModulosPantallas>();
        }

        public int modpt_Id { get; set; }
        public int mod_Id { get; set; }
        public string modpt_Descripcion { get; set; }
        public string modpt_Url { get; set; }
        public string modpt_Icono { get; set; }
        public int? modpt_Orden { get; set; }
        public bool modpt_EsActivo { get; set; }

        public virtual tbModulos Modulo { get; set; }
        public virtual ICollection<tbRolModulosPantallas> tbRolModulosPantallas { get; set; }
    }
}