// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbModulos
    {
        public tbModulos()
        {
            tbRolModulos = new HashSet<tbRolModulos>();
            tbRolModuloPermisos = new HashSet<tbRolModuloPermisos>();
            tbModulosPantallas = new HashSet<tbModulosPantallas>();
        }

        public int Mod_Id { get; set; }
        public string Mod_Nombre { get; set; }
        public string Mod_Descripcion { get; set; }
        public string Mod_Icono { get; set; }
        public string Mod_Url { get; set; }
        public int? Mod_Orden { get; set; }
        public bool Mod_EsActivo { get; set; }
        public DateTime Mod_FechaCreacion { get; set; }
        public int comp_Id { get; set; }

        public virtual tbComponentes Componente { get; set; }
        public virtual ICollection<tbRolModulos> tbRolModulos { get; set; }
        public virtual ICollection<tbRolModuloPermisos> tbRolModuloPermisos { get; set; }
        public virtual ICollection<tbModulosPantallas> tbModulosPantallas { get; set; }
    }
}