// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbPermisos
    {
        public tbPermisos()
        {
            tbRolModuloPermisos = new HashSet<tbRolModuloPermisos>();
        }

        public int Per_Id { get; set; }
        public string Per_Nombre { get; set; }
        public string Per_Descripcion { get; set; }
        public bool Per_EsActivo { get; set; }

        public virtual ICollection<tbRolModuloPermisos> tbRolModuloPermisos { get; set; }
    }
}