// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRegistroEventos
    {
        /// <summary>
        ///  Id identificador de la tabla
        /// </summary>
        public long Evt_Id { get; set; }
        /// <summary>
        /// Número que hace referencia al ID del tipo de evento
        /// </summary>
        public int? Tpevt_Id { get; set; }
        /// <summary>
        /// Id identificador del usuario del sistema que realizará el evento
        /// </summary>
        public int? Evt_Usu_Id { get; set; }
        /// <summary>
        /// Detalles del evento
        /// </summary>
        public string Evt_Detalles { get; set; }
        /// <summary>
        /// Navegador del usuario que realizará el evento
        /// </summary>
        public string Evt_UserAgent { get; set; }
        /// <summary>
        /// Dirección IP del usuario que realizará el evento
        /// </summary>
        public string Evt_DireccionIP { get; set; }
        /// <summary>
        /// Estado anterior del evento
        /// </summary>
        public string Evt_EstadoAnterior { get; set; }
        /// <summary>
        /// Nuevo estado del evento
        /// </summary>
        public string Evt_NuevoEstado { get; set; }
        /// <summary>
        /// Fecha de creación del evento
        /// </summary>
        public DateTime? Evt_FechaCreacion { get; set; }
    }
}