// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRolModulosPantallas
    {
        public int rolpt_Id { get; set; }
        public int modpt_Id { get; set; }
        public int rol_Id { get; set; }
        public DateTime rolpt_FechaAsignacion { get; set; }

        public virtual tbModulosPantallas ModuloPantalla { get; set; }
        public virtual tbRoles Rol { get; set; }
    }
}