// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
            tbRolModulos = new HashSet<tbRolModulos>();
            tbRolModuloPermisos = new HashSet<tbRolModuloPermisos>();
            tbRolModulosPantallas = new HashSet<tbRolModulosPantallas>();
            tbRolesUsuarios = new HashSet<tbRolesUsuarios>();
        }

        public int Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public bool Rol_EsActivo { get; set; }
        public bool Rol_EsEliminado { get; set; }
        public DateTime Rol_FechaCreacion { get; set; }
        public DateTime? Rol_FechaModificacion { get; set; }

        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
        public virtual ICollection<tbRolModulos> tbRolModulos { get; set; }
        public virtual ICollection<tbRolModuloPermisos> tbRolModuloPermisos { get; set; }
        public virtual ICollection<tbRolModulosPantallas> tbRolModulosPantallas { get; set; }
        public virtual ICollection<tbRolesUsuarios> tbRolesUsuarios { get; set; }
    }
}