// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class tbRolModuloPermisos
    {
        public int RolModPer_Id { get; set; }
        public int Rol_Id { get; set; }
        public int Mod_Id { get; set; }
        public int Per_Id { get; set; }
        public DateTime RolModPer_FechaAsignacion { get; set; }

        public virtual tbRoles Rol { get; set; }
        public virtual tbModulos Modulo { get; set; }
        public virtual tbPermisos Permiso { get; set; }
    }
}