// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbRolesUsuarios = new HashSet<tbRolesUsuarios>();
        }

        public int usu_Id { get; set; }
        public int Emp_Id { get; set; }
        public string Usu_Nombre { get; set; }
        public string Usu_PasswordHash { get; set; }
        public int Rol_Id { get; set; }
        public string Usu_Ip { get; set; }
        public bool Usu_EsActivo { get; set; }
        public bool Usu_Suspendido { get; set; }
        public bool Usu_EsEliminado { get; set; }
        public DateTime Usu_FechaCreacion { get; set; }
        public DateTime? Usu_fechaModificacion { get; set; }
        public string usu_ImagenPerfil { get; set; }
        public bool? usu_Logueado { get; set; }
        public DateTime? usu_UltimoAcceso { get; set; }
        public int? usu_IntentosFallidos { get; set; }
        public DateTime? usu_FechaBloqueo { get; set; }

        public virtual tbRoles Rol { get; set; }
        public virtual ICollection<tbRolesUsuarios> tbRolesUsuarios { get; set; }
    }
}