// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_General_Departamentos_DetailResult
    {
        public int depto_Id { get; set; }
        public string depto_Codigo { get; set; }
        public string depto_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime depto_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? depto_FechaModifica { get; set; }
    }
}
