// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_General_Departamentos_DropdownResult
    {
/// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int depto_Id { get; set; }
/// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string depto_Descripcion { get; set; }
    }
}
