// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_General_Municipios_DropdownResult
    {
        public int mpio_Id { get; set; }
        public string mpio_Descripcion { get; set; }
    }
}
