// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_General_Municipios_FindResult
    {
        public int mpio_Id { get; set; }
        public string mpio_Codigo { get; set; }
        public string mpio_Descripcion { get; set; }
        public int depto_Id { get; set; }
        public string codigoDept { get; set; }
        public string codigo { get; set; }
    }
}
