// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Dtoado del procedimiento almacenado de listado de recepciones de mercancía.
    /// </summary>
    public partial class InventarioRecepcionesMercanciaListDto
    {
        /// <summary>
        /// Obtiene o establece el ID de la recepción.
        /// </summary>
        public int recepId { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción de la recepción.
        /// </summary>
        public string recepDescripcion { get; set; }

        /// <summary>
        /// Obtiene o establece la fecha de la recepción.
        /// </summary>
        public DateTime recepFecha { get; set; }

        /// <summary>
        /// Obtiene o establece el ID del refugio.
        /// </summary>
        public int refgId { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del refugio.
        /// </summary>
        public string refgNombre { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo de recepción.
        /// </summary>
        public string recepTipoRecepcion { get; set; }

        /// <summary>
        /// Obtiene o establece el número de documento.
        /// </summary>
        public string recepNumeroDocumento { get; set; }
    }
}
