// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    public partial class InventarioEntradasDetallesFindDto
    {
        public int entdetId { get; set; }
        public int entId { get; set; }
        public int itmId { get; set; }
        public decimal entdetCantidad { get; set; }
    }
}
