// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// ado del procedimiento almacenado de detalle de recepción de mercancía.
    /// </summary>
    public partial class InventarioRecepcionesMercanciaDetailDto
    {
        /// <summary>
        /// Obtiene o establece el ID de la recepción.
        /// </summary>
        public int recep_Id { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción de la recepción.
        /// </summary>
        public string recep_Descripcion { get; set; }

        /// <summary>
        /// Obtiene o establece la fecha de la recepción.
        /// </summary>
        public DateTime recep_Fecha { get; set; }

        /// <summary>
        /// Obtiene o establece el ID del refugio.
        /// </summary>
        public int refg_Id { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del refugio.
        /// </summary>
        public string refg_Nombre { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo de recepción.
        /// </summary>
        public string recep_TipoRecepcion { get; set; }

        /// <summary>
        /// Obtiene o establece el ID del origen.
        /// </summary>
        public int? recep_OrigenId { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del origen.
        /// </summary>
        public string proc_Descripcion { get; set; }

        /// <summary>
        /// Obtiene o establece el número de documento.
        /// </summary>
        public string recep_NumeroDocumento { get; set; }
    }
}
