// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class InventarioCategoriasDetailDto
    {
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int catId { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string catDescripcion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioCreacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime catFechaCrea { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioModificacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? catFechaModifica { get; set; }
    }
}
