// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    public partial class InventarioEntradasDetallesFindDto
    {
        public int entdet_Id { get; set; }
        public int ent_Id { get; set; }
        public int itm_Id { get; set; }
        public decimal entdet_Cantidad { get; set; }
    }
}
