// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla de recepciones de mercancía.
    /// </summary>
    public partial class RecepcionesMercanciaDto
    { 

        /// <summary>
        /// Identificador único de la recepción de mercancía.
        /// </summary>
        public int recepId { get; set; }

        /// <summary>
        /// Descripción de la recepción.
        /// </summary>
        public string recepDescripcion { get; set; }

        /// <summary>
        /// Fecha de la recepción.
        /// </summary>
        public DateTime recepFecha { get; set; }

        /// <summary>
        /// Identificador del refugio.
        /// </summary>
        public int refgId { get; set; }

        /// <summary>
        /// Indica si el registro está eliminado.
        /// </summary>
        public bool recepEsEliminado { get; set; }

        /// <summary>
        /// Identificador del usuario que creó el registro.
        /// </summary>
        public int recepUsuarioCrea { get; set; }

        /// <summary>
        /// Fecha de creación del registro.
        /// </summary>
        public DateTime recepFechaCrea { get; set; }

        /// <summary>
        /// Identificador del usuario que modificó el registro.
        /// </summary>
        public int? recepUsuarioModifica { get; set; }

        /// <summary>
        /// Fecha de modificación del registro.
        /// </summary>
        public DateTime? recepFechaModifica { get; set; }

        /// <summary>
        /// Tipo de recepción (Compra, Donación, etc.).
        /// </summary>
        public string recepTipoRecepcion { get; set; }

        /// <summary>
        /// Identificador del origen/procedencia.
        /// </summary>
        public int? recepOrigenId { get; set; }

        /// <summary>
        /// Número de documento asociado a la recepción.
        /// </summary>
        public string recepNumeroDocumento { get; set; } 
    }
}
