// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbItems = new HashSet<tbItems>();
        }

        /// <summary>
        /// Identificador único de la tabla Categorias.
        /// </summary>
        public int catId { get; set; }
        public string catDescripcion { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool catEsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int catUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime catFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? catUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? catFechaModifica { get; set; }

        public virtual tbUsuarios catUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbItems> tbItems { get; set; }
    }
}