// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_ViasAdministracion_DetailResult
    {
        public int viaAdmin_Id { get; set; }
        public string viaAdmin_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? viaAdmin_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? viaAdmin_FechaModifica { get; set; }
    }
}
