// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposMedicamento_FindResult
    {
        public int tipoMed_Id { get; set; }
        public string tipoMed_Descripcion { get; set; }
        public int tipoMed_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? tipoMed_FechaCrea { get; set; }
        public int? tipoMed_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? tipoMed_FechaModifica { get; set; }

        public bool tipoMed_EsActivo { get; set; }
    }
}
