// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposMedicamento_DetailResult
    {
        public int tipoMed_Id { get; set; }
        public string tipoMed_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? tipoMed_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? tipoMed_FechaModifica { get; set; }
    }
}
