// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_Gravedades_FindResult
    {
        public int grav_Id { get; set; }
        public string grav_Descripcion { get; set; }
        public int grav_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? grav_FechaCrea { get; set; }
        public int? grav_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? grav_FechaModifica { get; set; }

        public bool grav_EsActivo { get; set; }
    }
}
