// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposMedicamento_ListResult
    {
        public int tipoMed_Id { get; set; }
        public string tipoMed_Descripcion { get; set; }
    }
}
