// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposEsterilizacion_DetailResult
    {
        public int tipoEst_Id { get; set; }
        public string tipoEst_Descripcion { get; set; }
        public string tipoEst_Sexo { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? tipoEst_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? tipoEst_FechaModifica { get; set; }
    }
}
