// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposConsulta_DropdownResult
    {
        public int tipoCon_Id { get; set; }
        public string tipoCon_Descripcion { get; set; }
    }
}
