// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposConsulta_DetailResult
    {
        public int tipoCon_Id { get; set; }
        public string tipoCon_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? tipoCon_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? tipoCon_FechaModifica { get; set; }
    }
}
