// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_ViasAdministracion_FindResult
    {
        public int viaAdmin_Id { get; set; }
        public string viaAdmin_Descripcion { get; set; }
        public int viaAdmin_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? viaAdmin_FechaCrea { get; set; }
        public int? viaAdmin_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? viaAdmin_FechaModifica { get; set; }
    }
}
