// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_Gravedades_DetailResult
    {
        public int grav_Id { get; set; }
        public string grav_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? grav_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? grav_FechaModifica { get; set; }
    }
}
