// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposParasito_ListResult
    {
        public int tipoPar_Id { get; set; }
        public string tipoPar_Descripcion { get; set; }
        public string tipoPar_Categoria { get; set; }

        public string tipoPar_EsActivo { get; set; }
    }
}
