// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposEsterilizacion_FindResult
    {
        public int tipoEst_Id { get; set; }
        public string tipoEst_Descripcion { get; set; }
        public string tipoEst_Sexo { get; set; }
        public int tipoEst_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? tipoEst_FechaCrea { get; set; }
        public int? tipoEst_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? tipoEst_FechaModifica { get; set; }
    }
}
