// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposParasito_FindResult
    {
        public int tipoPar_Id { get; set; }
        public string tipoPar_Descripcion { get; set; }
        public string tipoPar_Categoria { get; set; }
        public int tipoPar_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? tipoPar_FechaCrea { get; set; }
        public int? tipoPar_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? tipoPar_FechaModifica { get; set; }

        public bool tipoPar_EsActivo { get; set; }
    }
}
