// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposParasito_DetailResult
    {
        public int tipoPar_Id { get; set; }
        public string tipoPar_Descripcion { get; set; }
        public string tipoPar_Categoria { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? tipoPar_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? tipoPar_FechaModifica { get; set; }
    }
}
