// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Medico_TiposConsulta_ListResult
    {
        /// <summary>
        /// Obtiene o establece el ID del tipo de consulta.
        /// </summary>
        public int tipoCon_Id { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción del tipo de consulta.
        /// </summary>
        public string tipoCon_Descripcion { get; set; }

        public string tipoCon_EsActivo { get; set; }
    }
}
