// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Medico_TiposConsulta_FindResult
    {
        public int tipoCon_Id { get; set; }
        public string tipoCon_Descripcion { get; set; }
        public int tipoCon_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime? tipoCon_FechaCrea { get; set; }
        public int? tipoCon_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? tipoCon_FechaModifica { get; set; }
    }
}
