// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbGravedades
    {
        /// <summary>
        /// Identificador único de la gravedad.
        /// </summary>
        public int grav_Id { get; set; }

        /// <summary>
        /// Descripción del nivel de gravedad.
        /// </summary>
        public string grav_Descripcion { get; set; }

        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool? grav_EsActivo { get; set; }
        public bool grav_EsEliminado { get; set; }

        public int grav_UsuarioCrea { get; set; }
        public DateTime grav_FechaCrea { get; set; }
        public int? grav_UsuarioModifica { get; set; }
        public DateTime? grav_FechaModifica { get; set; }

        public virtual tbUsuarios grav_UsuarioCreaNavigation { get; set; }
    }
}
