// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbTiposConsulta
    {
        /// <summary>
        /// Identificador único del tipo de consulta.
        /// </summary>
        public int tipoCon_Id { get; set; }

        /// <summary>
        /// Descripción del tipo de consulta médica.
        /// </summary>
        public string tipoCon_Descripcion { get; set; }

        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool tipoCon_EsEliminado { get; set; }

        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int tipoCon_UsuarioCrea { get; set; }

        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime tipoCon_FechaCrea { get; set; }

        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? tipoCon_UsuarioModifica { get; set; }

        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? tipoCon_FechaModifica { get; set; }

        public virtual tbUsuarios tipoCon_UsuarioCreaNavigation { get; set; }
    }
}
