// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbTiposParasito
    {
        /// <summary>
        /// Identificador único del tipo de parásito.
        /// </summary>
        public int tipoPar_Id { get; set; }

        /// <summary>
        /// Descripción del tipo de parásito.
        /// </summary>
        public string tipoPar_Descripcion { get; set; }

        /// <summary>
        /// Categoría del parásito (Externo o Interno).
        /// </summary>
        public string tipoPar_Categoria { get; set; }

        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool tipoPar_EsEliminado { get; set; }

        public int tipoPar_UsuarioCrea { get; set; }
        public DateTime tipoPar_FechaCrea { get; set; }
        public int? tipoPar_UsuarioModifica { get; set; }
        public DateTime? tipoPar_FechaModifica { get; set; }

        public virtual tbUsuarios tipoPar_UsuarioCreaNavigation { get; set; }
    }
}
