// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbTiposEsterilizacion
    {
        /// <summary>
        /// Identificador único del tipo de esterilización.
        /// </summary>
        public int tipoEst_Id { get; set; }

        /// <summary>
        /// Descripción del tipo de esterilización.
        /// </summary>
        public string tipoEst_Descripcion { get; set; }

        /// <summary>
        /// Sexo aplicable para este tipo de esterilización (Macho, Hembra, Ambos).
        /// </summary>
        public string tipoEst_Sexo { get; set; }

        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool tipoEst_EsEliminado { get; set; }

        public int tipoEst_UsuarioCrea { get; set; }
        public DateTime tipoEst_FechaCrea { get; set; }
        public int? tipoEst_UsuarioModifica { get; set; }
        public DateTime? tipoEst_FechaModifica { get; set; }

        public virtual tbUsuarios tipoEst_UsuarioCreaNavigation { get; set; }
    }
}
