// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbViasAdministracion
    {
        /// <summary>
        /// Identificador único de la vía de administración.
        /// </summary>
        public int viaAdmin_Id { get; set; }

        /// <summary>
        /// Descripción de la vía de administración.
        /// </summary>
        public string viaAdmin_Descripcion { get; set; }

        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool? viaAdmin_EsActivo { get; set; }
        public bool viaAdmin_EsEliminado { get; set; }

        public int viaAdmin_UsuarioCrea { get; set; }
        public DateTime viaAdmin_FechaCrea { get; set; }
        public int? viaAdmin_UsuarioModifica { get; set; }
        public DateTime? viaAdmin_FechaModifica { get; set; }

        public virtual tbUsuarios viaAdmin_UsuarioCreaNavigation { get; set; }
    }
}
