// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PersonasDto
    { 

        /// <summary>
        /// Identificador único de la tabla Personas.
        /// </summary>
        public int perId { get; set; }
        public string perIdentidad { get; set; }
        public string perPrimerNombre { get; set; }
        public string perSegundoNombre { get; set; }
        public string perApellidoPaterno { get; set; }
        public string perApellidoMaterno { get; set; }
        public DateTime perFechaNacimiento { get; set; }
        public string perDomicilio { get; set; }
        public string perTelefono { get; set; }
        public string perCorreo { get; set; }
        public bool perEsEliminado { get; set; }
        public int perUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime perFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? perUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? perFechaModifica { get; set; }
         
    }
}