// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class tbDepartamentos
    {
        /// <summary>
        /// Constructor de la clase.
        /// </summary>
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
            tbRefugios = new HashSet<tbRefugios>();
        }

        /// <summary>
        /// Identificador único de la tabla Departamentos.
        /// </summary>
        public int deptoId { get; set; }
        /// <summary>
        /// Código administrativo único del departamento.
        /// </summary>
        public string deptoCodigo { get; set; }
        /// <summary>
        /// Nombre del departamento.
        /// </summary>
        public string deptoDescripcion { get; set; }
        /// <summary>
        /// Ciudad capital del departamento.
        /// </summary>
        public string deptoCapital { get; set; }
        /// <summary>
        /// Población del departamento.
        /// </summary>
        public int? deptoPoblacion { get; set; }
        /// <summary>
        /// Área en kilómetros cuadrados del departamento.
        /// </summary>
        public decimal? deptoAreaKm2 { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool deptoEsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int deptoUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime deptoFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? deptoUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? deptoFechaModifica { get; set; }

        public virtual tbUsuarios deptoUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
        public virtual ICollection<tbRefugios> tbRefugios { get; set; }
    }
}