// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class tbMunicipios
    {
        /// <summary>
        /// Constructor de la clase.
        /// </summary>
        public tbMunicipios()
        {
            tbRefugios = new HashSet<tbRefugios>();
        }

        /// <summary>
        /// Identificador único de la tabla Municipios.
        /// </summary>
        public int mpioId { get; set; }
        public string mpioCodigo { get; set; }
        /// <summary>
        /// alguna descrip
        /// </summary>
        public string mpioDescripcion { get; set; }
        public int deptoId { get; set; }
        /// <summary>
        /// ssssssfdfdf
        /// </summary>
        public bool mpioEsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int mpioUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime mpioFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? mpioUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? mpioFechaModifica { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual tbUsuarios mpioUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbRefugios> tbRefugios { get; set; }
    }
}