// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class EventosVoluntariosDto
    {
        public int evevolId { get; set; }
        public int eveId { get; set; }
        public int volId { get; set; }

    }
}