// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class HistorialMedicoVacunasDto
    {
        public int medicId { get; set; }
        public int vacId { get; set; }

        public virtual HistorialMedicoDto medic { get; set; }
        public virtual VacunasDto vac { get; set; }
    }
}