// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class RazasDto
    { 
        /// <summary>
        /// Número único que identifica el registro.
        /// </summary>
        public int razaId { get; set; }
        public string razaDescripcion { get; set; }
        /// <summary>
        /// Tamaño de la raza (pequeño, mediano, grande, gigante)
        /// </summary>
        public string razaTamano { get; set; }
        /// <summary>
        /// Tipo de animal (perro, gato, etc.)
        /// </summary>
        public string razaTipoAnimal { get; set; }
        /// <summary>
        /// Tipo de pelaje (corto, largo, rizado, sin pelo)
        /// </summary>
        public string razaTipoPelaje { get; set; }
        /// <summary>
        /// Foto/URL de imagen representativa de la raza
        /// </summary>
        public string razaImagenUrl { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool razaEsEliminado { get; set; }
        public int razaUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime razaFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? razaUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? razaFechaModifica { get; set; }
         
    }
}