// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioEmpleadosDetailDto
    {
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int empId { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string empCodigo { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perPrimerNombre { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perSegundoNombre { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perApellidoPaterno { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perApellidoMaterno { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perIdentidad { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime perFechaNacimiento { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perDomicilio { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perTelefono { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string perCorreo { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string cagDescripcion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string refgNombre { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string EsActivo { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioCreacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime perFechaCrea { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioModificacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? perFechaModifica { get; set; }
    }
}
