// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa el Dtoado de RefugioAdopcionesList.
    /// </summary>
    public partial class RefugioAdopcionesListDto
    {
        /// <summary>
        /// Identificador de la mascota.
        /// </summary>
        public int mascId { get; set; }

        /// <summary>
        /// Nombre de la mascota.
        /// </summary>
        public string mascNombre { get; set; }

        /// <summary>
        /// Descripción de la raza.
        /// </summary>
        public string razaDescripcion { get; set; }

        /// <summary>
        /// Tipo de animal (por ejemplo: Perro, Gato).
        /// </summary>
        public string razaTipoAnimal { get; set; }

        /// <summary>
        /// Edad de la mascota.
        /// </summary>
        public int mascEdad { get; set; }

        /// <summary>
        /// Sexo de la mascota.
        /// </summary>
        public string mascSexo { get; set; }

        /// <summary>
        /// Indica si la mascota ya fue adoptada.
        /// </summary>
        public bool mascEsAdoptado { get; set; }

        /// <summary>
        /// Indica si la mascota está reservada.
        /// </summary>
        public bool mascEsReservado { get; set; }

        /// <summary>
        /// Cantidad de solicitantes asociados a la mascota.
        /// </summary>
        public int CantidadSolicitantes { get; set; }
    }
}

