// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioEmpleadosCargosFindDto
    {
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int cagId { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string cagDescripcion { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public decimal? cagSalario { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool cagEsActivo { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int cagUsuarioCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime cagFechaCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int? cagUsuarioModifica { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioModifica { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? cagFechaModifica { get; set; }
    }
}
