// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioVacunasFindDto
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int vac_Id { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string vac_Descripcion { get; set; }

        /// <summary>
        /// Animal al que va dirigida la vacuna.
        /// </summary>
        public string vacu_Especie { get; set; }

        /// <summary>
        /// Cantidad y vía de aplicación.
        /// </summary>
        public string vacu_DosisRecomendada { get; set; }

        /// <summary>
        /// Tiempo antes de repetir dosis.
        /// </summary>
        public string vacu_PeriodoRefuerzo { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool vac_EsActivo { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int vac_UsuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime vac_FechaCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int? vac_UsuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? vac_FechaModifica { get; set; }
    }
}
