// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioRazasListDto
    {

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public long? Fila { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int raza_Id { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_Descripcion { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_Tamano { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_TipoAnimal { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_TipoPelaje { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_ImagenUrl { get; set; }
    }


}
