// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioVacunasFindDto
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int vacId { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string vacDescripcion { get; set; }

        /// <summary>
        /// Animal al que va dirigida la vacuna.
        /// </summary>
        public string vacuEspecie { get; set; }

        /// <summary>
        /// Cantidad y vía de aplicación.
        /// </summary>
        public string vacuDosisRecomendada { get; set; }

        /// <summary>
        /// Tiempo antes de repetir dosis.
        /// </summary>
        public string vacuPeriodoRefuerzo { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool vacEsActivo { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int vacUsuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime vacFechaCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int? vacUsuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? vacFechaModifica { get; set; }
    }
}
