// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Contracts.DTOs
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class RefugioHistorialMedicoDetailDto
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int medicId { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string mascNombre { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string razaDescripcion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool medicEsterilizacion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int comId { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string comDescripcion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string medicSaludCuidado { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string medicInformacionAdicional { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool medicEsEliminado { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioCreacion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime medicFechaCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioModificacion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? medicFechaModifica { get; set; }
    }
}
