// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbAdopciones
    {
        public int adopId { get; set; }
        public int solId { get; set; }
        public string adopEstado { get; set; }
        public bool adopEsEliminado { get; set; }
        public int adopUsuarioCrea { get; set; }
        public DateTime adopFechaCrea { get; set; }
        public int? adopUsuarioModifica { get; set; }
        public DateTime? adopFechaModifica { get; set; }

        public virtual tbUsuarios adopUsuarioCreaNavigation { get; set; }
        public virtual tbSolicitudes sol { get; set; }
    }
}