// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbComportamientos
    {
        public tbComportamientos()
        {
            tbHistorialMedico = new HashSet<tbHistorialMedico>();
        }

        public int comId { get; set; }
        public string comDescripcion { get; set; }
        public bool comEsEliminado { get; set; }
        public int comUsuarioCrea { get; set; }
        public DateTime comFechaCrea { get; set; }
        public int? comUsuarioModifica { get; set; }
        public DateTime? comFechaModifica { get; set; }

        public virtual ICollection<tbHistorialMedico> tbHistorialMedico { get; set; }
    }
}