// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbEmpleadosCargos
    {
        public tbEmpleadosCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        /// <summary>
        /// Identificador único de la tabla Empleados Cargos.
        /// </summary>
        public int cagId { get; set; }
        public string cagDescripcion { get; set; }
        public decimal? cagSalario { get; set; }
        public bool? cagEsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool cagEsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int cagUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime cagFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? cagUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? cagFechaModifica { get; set; }

        public virtual tbUsuarios cagUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}