// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbEmpleados
    {
        /// <summary>
        /// Identificador único de la tabla Empleados.
        /// </summary>
        public int empId { get; set; }
        public string empCodigo { get; set; }
        public int perId { get; set; }
        public int refgId { get; set; }
        public int cagId { get; set; }
        public bool? empEsActivo { get; set; }

        public virtual tbEmpleadosCargos cag { get; set; }
        public virtual tbPersonas per { get; set; }
        public virtual tbRefugios refg { get; set; }
    }
}