// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbEventos
    {
        public tbEventos()
        {
            tbEventostbVoluntarios = new HashSet<tbEventostbVoluntarios>();
        }

        /// <summary>
        /// Identificador único de la tabla Eventos.
        /// </summary>
        public int eveId { get; set; }
        public string eveDescripcion { get; set; }
        public int refgId { get; set; }
        public TimeSpan eveHoraInicio { get; set; }
        public TimeSpan eveHoraFinal { get; set; }
        public DateTime eveFecha { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool eveEsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int eveUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime eveFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? eveUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? eveFechaModifica { get; set; }

        public virtual tbUsuarios eveUsuarioCreaNavigation { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbEventostbVoluntarios> tbEventostbVoluntarios { get; set; }
    }
}