// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbRefugios
    {
        public tbRefugios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbEventos = new HashSet<tbEventos>();
            tbMascotas = new HashSet<tbMascotas>();
        }

        /// <summary>
        /// Identificador único de la tabla Refugios.
        /// </summary>
        public int refgId { get; set; }
        public string refgNombre { get; set; }
        public string refgUbicacion { get; set; }
        public string refgRTN { get; set; }
        public string refgTelefono { get; set; }
        public string refgCorreo { get; set; }
        public int deptoId { get; set; }
        public int mpioId { get; set; }
        public string refgInformacionAdicional { get; set; }
        public bool? refgEsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool refgEsEliminado { get; set; }
        public int refgUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime refgFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? refgUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? refgFechaModifica { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual tbMunicipios mpio { get; set; }
        public virtual tbUsuarios refgUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbEventos> tbEventos { get; set; }
        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}