// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbSolicitudes
    {
        public tbSolicitudes()
        {
            tbAdopciones = new HashSet<tbAdopciones>();
        }

        /// <summary>
        /// Identificador único del registro.
        /// </summary>
        public int solId { get; set; }
        /// <summary>
        /// Identificador nacional de la persona.
        /// </summary>
        public string solIdentidad { get; set; }
        /// <summary>
        /// Nombre de la persona realiza la solicitud.
        /// </summary>
        public string solNombres { get; set; }
        /// <summary>
        /// Apellido de la persona que realiza la solicitud.
        /// </summary>
        public string solApellidos { get; set; }
        /// <summary>
        /// Numero de teléfono que corresponde al solicitante.
        /// </summary>
        public string solTelefono { get; set; }
        /// <summary>
        /// Servicio de red que permite la comunicación mediante correo eleectronico con el solicitante.
        /// </summary>
        public string solCorreo { get; set; }
        /// <summary>
        /// pendiente eliminar
        /// </summary>
        public DateTime solFecha { get; set; }
        /// <summary>
        /// Identificador de la mascota.
        /// </summary>
        public int mascId { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool solEsEliminado { get; set; }
        public int solUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime solFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? solUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? solFechaModifica { get; set; }

        public virtual tbMascotas masc { get; set; }
        public virtual tbUsuarios solUsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbAdopciones> tbAdopciones { get; set; }
    }
}