// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class tbVoluntarios
    {
        public tbVoluntarios()
        {
            tbEventostbVoluntarios = new HashSet<tbEventostbVoluntarios>();
        }

        /// <summary>
        /// Identificador único de la tabla Voluntarios.
        /// </summary>
        public int volId { get; set; }
        public int volHorasTrabajadas { get; set; }
        public int perId { get; set; }
        public bool volRecurrente { get; set; }

        public virtual tbPersonas per { get; set; }
        public virtual ICollection<tbEventostbVoluntarios> tbEventostbVoluntarios { get; set; }
    }
}