// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Contracts.DTOs
{
    public partial class VacunasDto
    { 

        /// <summary>
        /// Identificador único de la tabla Vacunas.
        /// </summary>
        public int vacId { get; set; }
        /// <summary>
        /// Nombre de la vacuna.
        /// </summary>
        public string vacDescripcion { get; set; }
        /// <summary>
        /// Animal al que va dirigida la vacuna (perro, gato, etc.)
        /// </summary>
        public string vacuEspecie { get; set; }
        /// <summary>
        /// Cantidad y vía de aplicación (ej. "2 ml SC")
        /// </summary>
        public string vacuDosisRecomendada { get; set; }
        /// <summary>
        /// Tiempo antes de repetir dosis (ej. "12 meses")
        /// </summary>
        public string vacuPeriodoRefuerzo { get; set; }
        public bool? vacEsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool vacEsEliminado { get; set; }
        public int vacUsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime vacFechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? vacUsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? vacFechaModifica { get; set; }
         
    }
}