// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Inventario_InventariosDetalles_ListResult
    {
        public int invdet_Id { get; set; }
        public string itm_Descripcion { get; set; }
        public int? invdet_Cantidad { get; set; }
    }
}
