// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Inventario_EntradasDetalles_DetailResult
    {
        public int entdet_Id { get; set; }
        public string itm_Descripcion { get; set; }
        public string itm_Codigo { get; set; }
        public string cat_Descripcion { get; set; }
        public decimal itm_Precio { get; set; }
        public int entdet_Cantidad { get; set; }
        public int entdet_UsuarioCrea { get; set; }
        public DateTime entdet_FechaCrea { get; set; }
        public int? entdet_UsuarioModifica { get; set; }
        public DateTime? entdet_FechaModifica { get; set; }
    }
}
