// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Inventario_EntradasDetalles_DetailResult
    {
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int entdet_Id { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int ent_Id { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string ent_Descripcion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int itm_Id { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string itm_Descripcion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int entdet_Cantidad { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool entdet_EsEliminado { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioCreacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime entdet_FechaCrea { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioModificacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? entdet_FechaModifica { get; set; }
    }
}
