// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Inventario_Entradas_DetailResult
    {
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int ent_Id { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string ent_Descripcion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string refg_Nombre { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public decimal? ent_SumaTotal { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime ent_Fecha { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioCreacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime ent_FechaCrea { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string UsuarioModificacion { get; set; }
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? ent_FechaModifica { get; set; }
    }
}
