// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Inventario_Inventarios_DetailResult
    {
        public int inv_Id { get; set; }
        public string inv_Descripcion { get; set; }
        public DateTime inv_Fecha { get; set; }
        public string refg_Nombre { get; set; }
        public int? inv_UsuarioCrea { get; set; }
        public DateTime inv_FechaCrea { get; set; }
        public int? inv_UsuarioModifica { get; set; }
        public DateTime? inv_FechaModifica { get; set; }
    }
}
