// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Inventario_Categorias_DetailResult
    {
        public int cat_Id { get; set; }
        public string cat_Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime cat_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? cat_FechaModifica { get; set; }
    }
}
