// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Inventario_EntradasDetalles_FindResult
    {
        public int ent_Id { get; set; }
        public int entdet_Id { get; set; }
        public int itm_Id { get; set; }
        public string itm_Descripcion { get; set; }
        public int entdet_Cantidad { get; set; }
        public bool entdet_EsEliminado { get; set; }
        public int entdet_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime entdet_FechaCrea { get; set; }
        public int? entdet_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? entdet_FechaModifica { get; set; }
    }
}
