// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbEntradas
    {
        public tbEntradas()
        {
            tbEntradasDetalles = new HashSet<tbEntradasDetalles>();
        }

        /// <summary>
        /// Identificador único de la tabla Entradas.
        /// </summary>
        public int ent_Id { get; set; }
        /// <summary>
        /// Información descriptiva de la entrada.
        /// </summary>
        public string ent_Descripcion { get; set; }
        /// <summary>
        /// Este es el ID del departamento que hace referencia al primary key de la tabla tbRefugios
        /// </summary>
        public int refg_Id { get; set; }
        public DateTime ent_Fecha { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool ent_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int? ent_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime ent_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? ent_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? ent_FechaModifica { get; set; }

        public virtual tbUsuarios ent_UsuarioCreaNavigation { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbEntradasDetalles> tbEntradasDetalles { get; set; }
    }
}