// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbExistencias
    {
        /// <summary>
        /// Identificador único de la tabla Existencias.
        /// </summary>
        public int exist_Id { get; set; }
        public int itm_Id { get; set; }
        public int refg_Id { get; set; }
        /// <summary>
        /// Cantidad actual en stock.
        /// </summary>
        public int exist_Stock { get; set; }
        /// <summary>
        /// Stock mínimo permitido.
        /// </summary>
        public int exist_StockMinimo { get; set; }
        /// <summary>
        /// Stock máximo recomendado.
        /// </summary>
        public int exist_StockMaximo { get; set; }
        /// <summary>
        /// Fecha de la última actualización del stock.
        /// </summary>
        public DateTime exist_FechaActualizacion { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool exist_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int exist_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime exist_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? exist_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? exist_FechaModifica { get; set; }

        public virtual tbItems itm { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual tbUsuarios exist_UsuarioCreaNavigation { get; set; }
    }
}