// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbInventarios
    {
        public tbInventarios()
        {
            tbInventariosDetalles = new HashSet<tbInventariosDetalles>();
        }

        /// <summary>
        /// Identificador único de la tabla Inventarios.
        /// </summary>
        public int inv_Id { get; set; }
        /// <summary>
        /// Información relevante que se desee agregar
        /// </summary>
        public string inv_Descripcion { get; set; }
        public DateTime inv_Fecha { get; set; }
        public int refg_Id { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool inv_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int? inv_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime inv_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? inv_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? inv_FechaModifica { get; set; }

        public virtual tbUsuarios inv_UsuarioCreaNavigation { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbInventariosDetalles> tbInventariosDetalles { get; set; }
    }
}