// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbInventariosDetalles
    {
        /// <summary>
        /// Identificador único de la tabla Inventarios Detalles.
        /// </summary>
        public int invdet_Id { get; set; }
        public int inv_Id { get; set; }
        public int itm_Id { get; set; }
        public int invdet_Existencia { get; set; }
        public int invdet_Stock { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool invdet_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int invdet_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime invdet_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? invdet_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? invdet_FechaModifica { get; set; }

        public virtual tbInventarios inv { get; set; }
        public virtual tbUsuarios invdet_UsuarioCreaNavigation { get; set; }
        public virtual tbItems itm { get; set; }
    }
}