// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbMovimientos
    {
        /// <summary>
        /// Identificador único de la tabla Movimientos.
        /// </summary>
        public int mov_Id { get; set; }
        public int itm_Id { get; set; }
        public int refg_Id { get; set; }
        /// <summary>
        /// Tipo de movimiento (Entrada, Salida).
        /// </summary>
        public string mov_TipoMovimiento { get; set; }
        /// <summary>
        /// Subtipo específico (Compra, Donación, Consumo, etc.).
        /// </summary>
        public string mov_SubTipo { get; set; }
        /// <summary>
        /// Cantidad del movimiento (positiva para entradas, negativa para salidas).
        /// </summary>
        public int mov_Cantidad { get; set; }
        /// <summary>
        /// Stock después de este movimiento.
        /// </summary>
        public int mov_StockResultante { get; set; }
        /// <summary>
        /// Precio unitario del ítem en este movimiento.
        /// </summary>
        public decimal mov_PrecioUnitario { get; set; }
        /// <summary>
        /// Fecha del movimiento.
        /// </summary>
        public DateTime mov_Fecha { get; set; }
        /// <summary>
        /// ID de la recepción (si es entrada).
        /// </summary>
        public int? recep_Id { get; set; }
        /// <summary>
        /// ID de la salida (si es salida).
        /// </summary>
        public int? sal_Id { get; set; }
        /// <summary>
        /// Observaciones adicionales.
        /// </summary>
        public string mov_Observaciones { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool mov_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int mov_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime mov_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? mov_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? mov_FechaModifica { get; set; }

        public virtual tbItems itm { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual tbRecepcionesMercancia recep { get; set; }
        public virtual tbSalidas sal { get; set; }
        public virtual tbUsuarios mov_UsuarioCreaNavigation { get; set; }
    }
}