// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa el detalle de recepciones de mercancía.
    /// </summary>
    public partial class tbRecepcionesDetalles
    {
        /// <summary>
        /// Identificador único del detalle de recepción.
        /// </summary>
        public int recdet_Id { get; set; }

        /// <summary>
        /// Identificador de la recepción de mercancía.
        /// </summary>
        public int recep_Id { get; set; }

        /// <summary>
        /// Identificador del item/producto.
        /// </summary>
        public int itm_Id { get; set; }

        /// <summary>
        /// Cantidad recibida.
        /// </summary>
        public decimal recdet_Cantidad { get; set; }

        /// <summary>
        /// Indica si el registro está eliminado.
        /// </summary>
        public bool recdet_EsEliminado { get; set; }

        /// <summary>
        /// Identificador del usuario que creó el registro.
        /// </summary>
        public int recdet_UsuarioCrea { get; set; }

        /// <summary>
        /// Fecha de creación del registro.
        /// </summary>
        public DateTime recdet_FechaCrea { get; set; }

        /// <summary>
        /// Identificador del usuario que modificó el registro.
        /// </summary>
        public int? recdet_UsuarioModifica { get; set; }

        /// <summary>
        /// Fecha de modificación del registro.
        /// </summary>
        public DateTime? recdet_FechaModifica { get; set; }

        /// <summary>
        /// Precio unitario del item.
        /// </summary>
        public decimal? recdet_PrecioUnitario { get; set; }

        /// <summary>
        /// Fecha de vencimiento del producto.
        /// </summary>
        public DateTime? recdet_FechaVencimiento { get; set; }

        /// <summary>
        /// Número de lote del producto.
        /// </summary>
        public string recdet_NumeroLote { get; set; }

        public virtual tbRecepcionesMercancia recep { get; set; }
        public virtual tbItems itm { get; set; }
        public virtual tbUsuarios recdet_UsuarioCreaNavigation { get; set; }
    }
}
