// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla de recepciones de mercancía.
    /// </summary>
    public partial class tbRecepcionesMercancia
    {
        /// <summary>
        /// Constructor de la clase.
        /// </summary>
        public tbRecepcionesMercancia()
        {
            tbRecepcionesDetalles = new HashSet<tbRecepcionesDetalles>();
        }

        /// <summary>
        /// Identificador único de la recepción de mercancía.
        /// </summary>
        public int recep_Id { get; set; }

        /// <summary>
        /// Descripción de la recepción.
        /// </summary>
        public string recep_Descripcion { get; set; }

        /// <summary>
        /// Fecha de la recepción.
        /// </summary>
        public DateTime recep_Fecha { get; set; }

        /// <summary>
        /// Identificador del refugio.
        /// </summary>
        public int refg_Id { get; set; }

        /// <summary>
        /// Indica si el registro está eliminado.
        /// </summary>
        public bool recep_EsEliminado { get; set; }

        /// <summary>
        /// Identificador del usuario que creó el registro.
        /// </summary>
        public int recep_UsuarioCrea { get; set; }

        /// <summary>
        /// Fecha de creación del registro.
        /// </summary>
        public DateTime recep_FechaCrea { get; set; }

        /// <summary>
        /// Identificador del usuario que modificó el registro.
        /// </summary>
        public int? recep_UsuarioModifica { get; set; }

        /// <summary>
        /// Fecha de modificación del registro.
        /// </summary>
        public DateTime? recep_FechaModifica { get; set; }

        /// <summary>
        /// Tipo de recepción (Compra, Donación, etc.).
        /// </summary>
        public string recep_TipoRecepcion { get; set; }

        /// <summary>
        /// Identificador del origen/procedencia.
        /// </summary>
        public int? recep_OrigenId { get; set; }

        /// <summary>
        /// Número de documento asociado a la recepción.
        /// </summary>
        public string recep_NumeroDocumento { get; set; }

        public virtual tbRefugios refg { get; set; }
        public virtual tbUsuarios recep_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbRecepcionesDetalles> tbRecepcionesDetalles { get; set; }
    }
}
