// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRecepcionesMercancia
    {
        public tbRecepcionesMercancia()
        {
            tbRecepcionesDetalles = new HashSet<tbRecepcionesDetalles>();
        }

        /// <summary>
        /// Identificador único de la tabla Recepciones de Mercancía.
        /// </summary>
        public int recep_Id { get; set; }
        /// <summary>
        /// Información relevante que se desee agregar.
        /// </summary>
        public string recep_Descripcion { get; set; }
        public DateTime recep_Fecha { get; set; }
        /// <summary>
        /// Tipo de recepción (Compra, Donación, Transferencia, etc.)
        /// </summary>
        public string recep_TipoRecepcion { get; set; }
        /// <summary>
        /// ID del origen de la recepción (proveedor, refugio origen, etc.)
        /// </summary>
        public int? recep_OrigenId { get; set; }
        /// <summary>
        /// Número de documento asociado (factura, orden de compra, etc.)
        /// </summary>
        public string recep_NumeroDocumento { get; set; }
        /// <summary>
        /// Este es el ID del refugio que hace referencia al primary key de la tabla tbRefugios.
        /// </summary>
        public int refg_Id { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool recep_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int recep_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime recep_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? recep_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? recep_FechaModifica { get; set; }

        public virtual tbUsuarios recep_UsuarioCreaNavigation { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbRecepcionesDetalles> tbRecepcionesDetalles { get; set; }
    }
}