// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRecepcionesDetalles
    {
        /// <summary>
        /// Identificador único de la tabla Recepciones Detalles.
        /// </summary>
        public int recdet_Id { get; set; }
        public int recep_Id { get; set; }
        public int itm_Id { get; set; }
        /// <summary>
        /// Cantidad recibida en esta recepción.
        /// </summary>
        public int recdet_Cantidad { get; set; }
        /// <summary>
        /// Precio unitario del ítem en esta recepción.
        /// </summary>
        public decimal recdet_PrecioUnitario { get; set; }
        /// <summary>
        /// Fecha de vencimiento del producto (si aplica).
        /// </summary>
        public DateTime? recdet_FechaVencimiento { get; set; }
        /// <summary>
        /// Número de lote del producto (si aplica).
        /// </summary>
        public string recdet_NumeroLote { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool recdet_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int recdet_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime recdet_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? recdet_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? recdet_FechaModifica { get; set; }

        public virtual tbRecepcionesMercancia recep { get; set; }
        public virtual tbUsuarios recdet_UsuarioCreaNavigation { get; set; }
        public virtual tbItems itm { get; set; }
    }
}