// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbSalidas
    {
        public tbSalidas()
        {
            tbSalidasDetalles = new HashSet<tbSalidasDetalles>();
        }

        /// <summary>
        /// Identificador único de la tabla Salidas.
        /// </summary>
        public int sal_Id { get; set; }
        /// <summary>
        /// Información relevante que se desee agregar.
        /// </summary>
        public string sal_Descripcion { get; set; }
        public DateTime sal_Fecha { get; set; }
        /// <summary>
        /// Tipo de salida (Consumo, Donación, Transferencia, Pérdida, etc.)
        /// </summary>
        public string sal_TipoSalida { get; set; }
        /// <summary>
        /// ID del destino de la salida (refugio destino, área de consumo, etc.)
        /// </summary>
        public int? sal_DestinoId { get; set; }
        /// <summary>
        /// Número de documento asociado (vale de salida, orden de transferencia, etc.)
        /// </summary>
        public string sal_NumeroDocumento { get; set; }
        /// <summary>
        /// Este es el ID del refugio que hace referencia al primary key de la tabla tbRefugios.
        /// </summary>
        public int refg_Id { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool sal_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int sal_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime sal_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? sal_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? sal_FechaModifica { get; set; }

        public virtual tbUsuarios sal_UsuarioCreaNavigation { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbSalidasDetalles> tbSalidasDetalles { get; set; }
    }
}