// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbSalidasDetalles
    {
        /// <summary>
        /// Identificador único de la tabla Salidas Detalles.
        /// </summary>
        public int saldet_Id { get; set; }
        public int sal_Id { get; set; }
        public int itm_Id { get; set; }
        /// <summary>
        /// Cantidad que sale del inventario.
        /// </summary>
        public int saldet_Cantidad { get; set; }
        /// <summary>
        /// Precio unitario del ítem al momento de la salida.
        /// </summary>
        public decimal saldet_PrecioUnitario { get; set; }
        /// <summary>
        /// Motivo específico de la salida.
        /// </summary>
        public string saldet_Motivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool saldet_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int saldet_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime saldet_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? saldet_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? saldet_FechaModifica { get; set; }

        public virtual tbSalidas sal { get; set; }
        public virtual tbUsuarios saldet_UsuarioCreaNavigation { get; set; }
        public virtual tbItems itm { get; set; }
    }
}