// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_Mascotas_ListResult
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int masc_Id { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public long? masc_Fila { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string masc_Nombre { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string raza_Descripcion { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string refg_Nombre { get; set; }
    }
}
