// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Procedencia_DropdownResult
    {
        public int proc_Id { get; set; }
        public string proc_Descripcion { get; set; }
    }
}
