// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Razas_FindResult
    {
        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public int? raza_UsuarioCrea { get; set; }
        public DateTime? raza_FechaCrea { get; set; }
        public int? raza_UsuarioModifica { get; set; }
        public DateTime? raza_FechaModifica { get; set; }
    }
}
