// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_EmpleadosCargos_FindResult
    {
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int cag_Id { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string cag_Descripcion { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public decimal? cag_Salario { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public bool cag_EsActivo { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int cag_UsuarioCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime cag_FechaCrea { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int? cag_UsuarioModifica { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioModifica { get; set; }
        
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? cag_FechaModifica { get; set; }
    }
}
