// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Voluntarios_FindResult
    {
        public int vol_Id { get; set; }
        public int vol_HorasTrabajadas { get; set; }
        public int per_Id { get; set; }
        public string per_PrimerNombre { get; set; }
        public string per_SegundoNombre { get; set; }
        public string per_ApellidoPaterno { get; set; }
        public string per_ApellidoMaterno { get; set; }
        public string per_Identidad { get; set; }
        public DateTime per_FechaNacimiento { get; set; }
        public string per_Domicilio { get; set; }
        public string per_Telefono { get; set; }
        public string per_Correo { get; set; }
        public bool vol_Recurrente { get; set; }
        public string estado { get; set; }
        public int per_UsuarioCrea { get; set; }
        public string usuarioCrea { get; set; }
        public DateTime per_FechaCrea { get; set; }
        public int? per_UsuarioModifica { get; set; }
        public string usuarioModifica { get; set; }
        public DateTime? per_FechaModifica { get; set; }
    }
}
