// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Refugios_DetailResult
    {
        public int refg_Id { get; set; }
        public string refg_Nombre { get; set; }
        public string refg_Ubicacion { get; set; }
        public string refg_RTN { get; set; }
        public string refg_Telefono { get; set; }
        public string refg_Correo { get; set; }
        public int depto_Id { get; set; }
        public int mpio_Id { get; set; }
        public string refg_InformacionAdicional { get; set; }
        public string EsActivo { get; set; }
        public int refg_UsuarioCrea { get; set; }
        public DateTime refg_FechaCrea { get; set; }
        public int? refg_UsuarioModifica { get; set; }
        public DateTime? refg_FechaModifica { get; set; }
    }
}
