// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_HistorialMedico_FindResult
    {
        public int medic_Id { get; set; }
        public string masc_Nombre { get; set; }
        public bool medic_Esterilizacion { get; set; }
        public string medic_Comportamiento { get; set; }
        public string medic_SaludCuidado { get; set; }
        public string medic_InformacionAdicional { get; set; }
        public int medic_UsuarioCrea { get; set; }
        public DateTime medic_FechaCrea { get; set; }
        public int? medic_UsuarioModifica { get; set; }
        public DateTime? medic_FechaModifica { get; set; }
    }
}
