// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Mascotas_ListResult
    {
        public int masc_Id { get; set; }
        public long? masc_Fila { get; set; }
        public string masc_Nombre { get; set; }
        public string raza_Descripcion { get; set; }
        public string refg_Nombre { get; set; }
        public bool masc_EsAdoptado { get; set; }
        public bool masc_EsReservado { get; set; }
    }
}
