// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_EmpleadosCargos_DetailResult
    {
        public int cag_Id { get; set; }
        public string cag_Descripcion { get; set; }
        public decimal? cag_Salario { get; set; }
        public string EsActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime cag_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? cag_FechaModifica { get; set; }
    }
}
