// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Voluntarios_ListResult
    {
        public int vol_Id { get; set; }
        public int vol_HorasTrabajadas { get; set; }
        public string vol_Nombres { get; set; }
        public string per_Identidad { get; set; }
    }
}
