// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Empleados_ListResult
    {
        public int emp_Id { get; set; }
        public string emp_Codigo { get; set; }
        public string emp_Nombres { get; set; }
        public string cag_Descripcion { get; set; }
        public string refg_Nombre { get; set; }
        public string EsActivo { get; set; }
    }
}
