// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_Adopciones_ListResult
    {
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public int adop_Id { get; set; }
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public int sol_Id { get; set; }
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public string adop_Estado { get; set; }
       /// <summary>
        /// Obtiene o establece el nombre de la mascota.
        /// </summary>
       public string masc_Nombre { get; set; }
       /// <summary>
        /// Obtiene o establece el nombre del adoptante.
        /// </summary>
       public string per_Nombre { get; set; }
       /// <summary>
        /// Obtiene o establece la fecha de creación.
        /// </summary>
       public DateTime adop_FechaCrea { get; set; }
    }
}
