// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Talla_DropdownResult
    {
        public int tall_Id { get; set; }
        public string tall_Descripcion { get; set; }
    }
}
