// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_Solicitudes_FindResult
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int sol_Id { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string sol_Identidad { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string sol_Nombres { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string sol_Apellidos { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string sol_Telefono { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string sol_Correo { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime sol_Fecha { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int masc_Id { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string masc_Nombre { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int sol_UsuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime sol_FechaCrea { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int? sol_UsuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string usuarioModifica { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public DateTime? sol_FechaModifica { get; set; }
    }
}
