// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_Adopciones_ListResult
    {
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public int adop_Id { get; set; }
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public int sol_Id { get; set; }
       /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
       public bool adop_EsAprobado { get; set; }
    }
}
