// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_CitaMedica_DetailResult
    {

        public int cita_Id { get; set; }
        public int masc_Id { get; set; }
        public string masc_Nombre { get; set; }
        public string raza_Descripcion { get; set; }
        public int com_Id { get; set; }
        public string com_Descripcion { get; set; }
        public DateTime cita_FechaConsulta { get; set; }
        public string cita_TipoConsulta { get; set; }
        public string cita_MotivoConsulta { get; set; }
        public string cita_Diagnostico { get; set; }
        public decimal? cita_Peso { get; set; }
        public decimal? cita_Temperatura { get; set; }
        public int? cita_FrecuenciaCardiaca { get; set; }
        public int? cita_FrecuenciaRespiratoria { get; set; }
        public int? vac_Id { get; set; }
        public string cita_MedicamentosRecetados { get; set; }
        public string cita_Dosificacion { get; set; }
        public string cita_ProcedimientosRealizados { get; set; }
        public string cita_ResultadosExamenes { get; set; }
        public DateTime? cita_ProximaCita { get; set; }
        public string cita_MotivoProximaCita { get; set; }
        public bool cita_EsEliminado { get; set; }
        public int cita_UsuarioCrea { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime cita_FechaCrea { get; set; }
        public int? cita_UsuarioModifica { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? cita_FechaModifica { get; set; }
    }
}
