// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_CitaMedica_ListResult
    {

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Mascota.
        /// </summary>
        public string Mascota { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Comportamiento.
        ///// </summary>
        //public string Comportamiento { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad FechaConsulta.
        ///// </summary>
        //public DateTime FechaConsulta { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad TipoConsulta.
        ///// </summary>
        //public string TipoConsulta { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad MotivoConsulta.
        ///// </summary>
        //public string MotivoConsulta { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Diagnostico.
        ///// </summary>
        //public string Diagnostico { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Peso.
        ///// </summary>
        //public int? Peso { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Temperatura.
        ///// </summary>
        //public int? Temperatura { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad FrecuenciaCardiaca.
        ///// </summary>
        //public int? FrecuenciaCardiaca { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad FrecuenciaRespiratoria.
        ///// </summary>
        //public int? FrecuenciaRespiratoria { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Vacuna.
        ///// </summary>
        //public string Vacuna { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad MedicamentosRecetados.
        ///// </summary>
        //public string MedicamentosRecetados { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad Dosificacion.
        ///// </summary>
        //public string Dosificacion { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad ProcedimientosRealizados.
        ///// </summary>
        //public string ProcedimientosRealizados { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad ResultadosExamenes.
        ///// </summary>
        //public string ResultadosExamenes { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad ProximaCita.
        ///// </summary>
        //public DateTime? ProximaCita { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad MotivoProximaCita.
        ///// </summary>
        //public string MotivoProximaCita { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad FechaCreacion.
        ///// </summary>
        //public DateTime FechaCreacion { get; set; }

        ///// <summary>
        ///// Obtiene o establece el valor de la propiedad FechaModificacion.
        ///// </summary>
        //public DateTime? FechaModificacion { get; set; }
    }
}
