// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_CitaMedica_ListResult
    {

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Id.
        /// </summary>
        public int cita_Id { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Mascota.
        /// </summary>
        public string masc_Nombre { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Comportamiento.
        /// </summary>
        public string cita_Comportamiento { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad FechaConsulta.
        /// </summary>
        public string cita_FechaConsulta { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad TipoConsulta.
        /// </summary>
        public string cita_TipoConsulta { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad MotivoConsulta.
        /// </summary>
        public string cita_MotivoConsulta { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Diagnostico.
        /// </summary>
        public string cita_Diagnostico { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Peso.
        /// </summary>
        public int? cita_Peso { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Temperatura.
        /// </summary>
        public int? cita_Temperatura { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad FrecuenciaCardiaca.
        /// </summary>
        public int? cita_FrecuenciaCardiaca { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad FrecuenciaRespiratoria.
        /// </summary>
        public int? cita_FrecuenciaRespiratoria { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Vacuna.
        /// </summary>
        public string cita_Vacuna { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad MedicamentosRecetados.
        /// </summary>
        public string cita_MedicamentosRecetados { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad Dosificacion.
        /// </summary>
        public string cita_Dosificacion { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad ProcedimientosRealizados.
        /// </summary>
        public string cita_ProcedimientosRealizados { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad ResultadosExamenes.
        /// </summary>
        public string cita_ResultadosExamenes { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad ProximaCita.
        /// </summary>
        public DateTime? cita_ProximaCita { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad MotivoProximaCita.
        /// </summary>
        public string cita_MotivoProximaCita { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad FechaCreacion.
        /// </summary>
        public DateTime cita_FechaCreacion { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad FechaModificacion.
        /// </summary>
        public DateTime? cita_FechaModificacion { get; set; }
    }
}
