// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    /// <summary>
    /// Entidad que representa la tabla.
    /// </summary>
    public partial class PR_Refugio_Vacunas_ListResult
    {
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public int vac_Id { get; set; }
        
        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string vac_Descripcion { get; set; }

        /// <summary>
        /// Animal al que va dirigida la vacuna.
        /// </summary>
        public string vacu_Especie { get; set; }

        /// <summary>
        /// Cantidad y vía de aplicación.
        /// </summary>
        public string vacu_DosisRecomendada { get; set; }

        /// <summary>
        /// Tiempo antes de repetir dosis.
        /// </summary>
        public string vacu_PeriodoRefuerzo { get; set; }

        /// <summary>
        /// Obtiene o establece el valor de la propiedad.
        /// </summary>
        public string EsActivo { get; set; }
    }
}
