// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Adopciones_ListResult
    {
        public int adop_Id { get; set; }
        public int sol_Id { get; set; }
        public bool adop_EsAprobado { get; set; }
    }
}
