// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetsHome.Common.Entities
{
    public partial class PR_Refugio_Vacunas_DetailResult
    {
        public int vac_Id { get; set; }
        public string vac_Descripcion { get; set; }
        public string EsActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime vac_FechaCrea { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? vac_FechaModifica { get; set; }
    }
}
