// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbDonaciones
    {
        public int dona_Id { get; set; }
        public string dona_TipoDonacion { get; set; }
        public string dona_NombreDonante { get; set; }
        public string dona_TelefonoDonante { get; set; }
        public string dona_EmailDonante { get; set; }
        public decimal? dona_MontoMonetario { get; set; }
        public string dona_DescripcionArticulos { get; set; }
        public decimal? dona_ValorEstimado { get; set; }
        public DateTime dona_FechaDonacion { get; set; }
        public string dona_Estado { get; set; }
        public string dona_Observaciones { get; set; }
        public int refg_Id { get; set; }
        public bool dona_EsEliminado { get; set; }
        public int dona_UsuarioCrea { get; set; }
        public DateTime dona_FechaCrea { get; set; }
        public int? dona_UsuarioModifica { get; set; }
        public DateTime? dona_FechaModifica { get; set; }

        public virtual tbRefugios refg { get; set; }
        public virtual tbUsuarios dona_UsuarioCreaNavigation { get; set; }
    }
}