// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbEmpleadosCargos
    {
        public tbEmpleadosCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        /// <summary>
        /// Identificador único de la tabla Empleados Cargos.
        /// </summary>
        public int cag_Id { get; set; }
        public string cag_Descripcion { get; set; }
        public decimal? cag_Salario { get; set; }
        public bool? cag_EsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool cag_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int cag_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime cag_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? cag_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? cag_FechaModifica { get; set; }

        public virtual tbUsuarios cag_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}