// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbEventos_tbVoluntarios
    {
        public int evevol_Id { get; set; }
        public int eve_Id { get; set; }
        public int vol_Id { get; set; }

        public virtual tbEventos eve { get; set; }
        public virtual tbVoluntarios vol { get; set; }
    }
}