// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbHistorialMedico_tbVacunas
    {
        public int medic_Id { get; set; }
        public int vac_Id { get; set; }

        public virtual tbHistorialMedico medic { get; set; }
        public virtual tbVacunas vac { get; set; }
    }
}