// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbMascotas
    {
        public tbMascotas()
        {
            tbHistorialMedico = new HashSet<tbHistorialMedico>();
            tbSolicitudes = new HashSet<tbSolicitudes>();
        }

        /// <summary>
        /// Identificador único de la tabla Mascotas.
        /// </summary>
        public int masc_Id { get; set; }
        public byte[] masc_Imagen { get; set; }
        public string masc_Nombre { get; set; }
        public int? raza_Id { get; set; }
        public int? masc_Edad { get; set; }
        public string masc_Sexo { get; set; }
        public decimal masc_Peso { get; set; }
        public decimal masc_Talla { get; set; }
        public string masc_Color { get; set; }
        public string masc_Historia { get; set; }
        public int refg_Id { get; set; }
        public int proc_Id { get; set; }
        public bool masc_EsAdoptado { get; set; }
        public bool masc_EsReservado { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool masc_EsEliminado { get; set; }
        /// <summary>
        /// Indica el identificador del usuario que creó el registro.
        /// </summary>
        public int masc_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime masc_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? masc_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? masc_FechaModifica { get; set; }

        public virtual tbUsuarios masc_UsuarioCreaNavigation { get; set; }
        public virtual tbProcedencias proc { get; set; }
        public virtual tbRazas raza { get; set; }
        public virtual tbRefugios refg { get; set; }
        public virtual ICollection<tbHistorialMedico> tbHistorialMedico { get; set; }
        public virtual ICollection<tbSolicitudes> tbSolicitudes { get; set; }
    }
}