// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbProcedencias
    {
        public tbProcedencias()
        {
            tbMascotas = new HashSet<tbMascotas>();
        }

        /// <summary>
        /// Identificador único de la tabla Procedencias.
        /// </summary>
        public int proc_Id { get; set; }
        public string proc_Descripcion { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool proc_EsEliminado { get; set; }
        public int proc_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime proc_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? proc_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? proc_FechaModifica { get; set; }

        public virtual tbUsuarios proc_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}