// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRazas
    {
        public tbRazas()
        {
            tbMascotas = new HashSet<tbMascotas>();
        }

        /// <summary>
        /// Número único que identifica el registro.
        /// </summary>
        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool raza_EsEliminado { get; set; }
        public int raza_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime raza_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? raza_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? raza_FechaModifica { get; set; }

        public virtual tbUsuarios raza_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}