// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbRefugios
    {
        public tbRefugios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbEntradas = new HashSet<tbEntradas>();
            tbEventos = new HashSet<tbEventos>();
            tbInventarios = new HashSet<tbInventarios>();
            tbMascotas = new HashSet<tbMascotas>();
        }

        /// <summary>
        /// Identificador único de la tabla Refugios.
        /// </summary>
        public int refg_Id { get; set; }
        public string refg_Nombre { get; set; }
        public string refg_Ubicacion { get; set; }
        public string refg_RTN { get; set; }
        public string refg_Telefono { get; set; }
        public string refg_Correo { get; set; }
        public int depto_Id { get; set; }
        public int mpio_Id { get; set; }
        public string refg_InformacionAdicional { get; set; }
        public bool? refg_EsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool refg_EsEliminado { get; set; }
        public int refg_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime refg_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? refg_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? refg_FechaModifica { get; set; }

        public virtual tbUsuarios refg_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbEntradas> tbEntradas { get; set; }
        public virtual ICollection<tbEventos> tbEventos { get; set; }
        public virtual ICollection<tbInventarios> tbInventarios { get; set; }
        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}