// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbSolicitudes
    {
        public tbSolicitudes()
        {
            tbAdopciones = new HashSet<tbAdopciones>();
        }

        /// <summary>
        /// Identificador único del registro.
        /// </summary>
        public int sol_Id { get; set; }
        /// <summary>
        /// Identificador nacional de la persona.
        /// </summary>
        public string sol_Identidad { get; set; }
        /// <summary>
        /// Nombre de la persona realiza la solicitud.
        /// </summary>
        public string sol_Nombres { get; set; }
        /// <summary>
        /// Apellido de la persona que realiza la solicitud.
        /// </summary>
        public string sol_Apellidos { get; set; }
        /// <summary>
        /// Numero de teléfono que corresponde al solicitante.
        /// </summary>
        public string sol_Telefono { get; set; }
        /// <summary>
        /// Servicio de red que permite la comunicación mediante correo eleectronico con el solicitante.
        /// </summary>
        public string sol_Correo { get; set; }
        /// <summary>
        /// pendiente eliminar
        /// </summary>
        public DateTime sol_Fecha { get; set; }
        /// <summary>
        /// Identificador de la mascota.
        /// </summary>
        public int masc_Id { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool sol_EsEliminado { get; set; }
        public int sol_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime sol_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? sol_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? sol_FechaModifica { get; set; }

        public virtual tbMascotas masc { get; set; }
        public virtual tbUsuarios sol_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbAdopciones> tbAdopciones { get; set; }
    }
}