// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace PetsHome.Common.Entities
{
    public partial class tbTallas
    {
        public int tall_Id { get; set; }
        public string tall_Descripcion { get; set; }
        public bool tall_EsEliminado { get; set; }
        public int tall_UsuarioCrea { get; set; }
        public DateTime tall_FechaCrea { get; set; }
        public int? tall_UsuarioModifica { get; set; }
        public DateTime? tall_FechaModifica { get; set; }
    }
}
