// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbVacunas
    {
        public tbVacunas()
        {
            tbHistorialMedico_tbVacunas = new HashSet<tbHistorialMedico_tbVacunas>();
        }

        /// <summary>
        /// Identificador único de la tabla Vacunas.
        /// </summary>
        public int vac_Id { get; set; }
        /// <summary>
        /// Nombre de la vacuna.
        /// </summary>
        public string vac_Descripcion { get; set; }
        public bool? vac_EsActivo { get; set; }
        /// <summary>
        /// Indica si el registro está desactivado permanentemente.
        /// </summary>
        public bool vac_EsEliminado { get; set; }
        public int vac_UsuarioCrea { get; set; }
        /// <summary>
        /// Registra la fecha en que se creó el registro.
        /// </summary>
        public DateTime vac_FechaCrea { get; set; }
        /// <summary>
        /// Indica el identificador del último usuario que modificó el registro.
        /// </summary>
        public int? vac_UsuarioModifica { get; set; }
        /// <summary>
        /// Registra la última fecha en que se modificó el registro.
        /// </summary>
        public DateTime? vac_FechaModifica { get; set; }

        public virtual tbUsuarios vac_UsuarioCreaNavigation { get; set; }
        public virtual ICollection<tbHistorialMedico_tbVacunas> tbHistorialMedico_tbVacunas { get; set; }
    }
}