// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetsHome.Common.Entities
{
    public partial class tbVoluntarios
    {
        public tbVoluntarios()
        {
            tbEventos_tbVoluntarios = new HashSet<tbEventos_tbVoluntarios>();
        }

        /// <summary>
        /// Identificador único de la tabla Voluntarios.
        /// </summary>
        public int vol_Id { get; set; }
        public int vol_HorasTrabajadas { get; set; }
        public int per_Id { get; set; }
        public bool vol_Recurrente { get; set; }

        public virtual tbPersonas per { get; set; }
        public virtual ICollection<tbEventos_tbVoluntarios> tbEventos_tbVoluntarios { get; set; }
    }
}